apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qps3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-qps3@sha256:320ef499fb7db4dbec06c5d277096aa2ece826b3704e1fbcdc4c9a79e2a1b233
        name: my-nodejs
        resources: {}
status: {}
